# Generated by Django 5.1 on 2024-08-21 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmuebles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('direccion', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('venta', 'Venta'), ('alquiler', 'Alquiler')], default='venta', max_length=255)),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('no disponible', 'No disponible'), ('activo', 'Activo'), ('inactivo', 'Inactivo')], default='disponible', max_length=255)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
