# Generated by Django 5.1 on 2024-09-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0002_inmuebles_disponibilidad_inmuebles_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmuebles',
            name='codigo',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
