# Generated by Django 5.1 on 2024-09-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0003_alter_inmuebles_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmuebles',
            name='n_baños',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='n_habitaciones',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
