# Generated by Django 5.1 on 2024-10-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0004_inmuebles_n_baños_inmuebles_n_habitaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmuebles',
            old_name='n_baños',
            new_name='n_banos',
        ),
    ]
