# Generated by Django 5.1 on 2024-10-09 15:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0005_rename_n_baños_inmuebles_n_banos'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmuebles',
            name='imagnes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None),
        ),
    ]
