# Generated by Django 5.1 on 2024-10-21 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0007_rename_imagnes_inmuebles_imagenes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmuebles',
            name='codigo',
        ),
    ]
