# Generated by Django 5.1 on 2024-10-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0009_inmuebles_documentos_inmuebles_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmuebles',
            name='observaciones',
            field=models.TextField(default='Sin observaciones'),
        ),
    ]
